jwt:
  secret: anNoLXNwcmluZ2Jvb3QtYW5kLWp3dC10dXRvcmlhbC10aGlzLWlzLWZvci1nZW5lcmF0aW5nLWp3dC1zZWNyZXRrZXktYmFzZTY0Cg==

security:
  oauth2:
    client:
      registration:
        kakao:
          client-id: #[REST API ?]
          redirect-url: http://localhost:8080/login/oauth2/code/kakao #[Redirect URI]
          authorization-grant-type: authorization_code
          client-authentication-method: POST
          client-name: Kakao
          scope:
            - profile_nickname
            - account_email
      provider:
        kakao:
          authorization-url: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id

# https://blog.naver.com/ghdalswl77/222711530197
# https://blog.naver.com/gentle_gaeran/223309922296