server:
  port : 5000
  servlet:
    encoding:
      force-response: true

spring:
  application:
    name: backend
  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}
    username: ${rds.username}
    password: ${rds.password}

jwt:
  secret: anNoLXNwcmluZ2Jvb3QtYW5kLWp3dC10dXRvcmlhbC10aGlzLWlzLWZvci1nZW5lcmF0aW5nLWp3dC1zZWNyZXRrZXktYmFzZTY0Cg==

security:
  oauth2:
    client:
      registration:
        kakao:
          client-id: {KAKAO_CLIENT_ID}
          client-secret: {KAKAO_CLIENT_SECRET}
          client-authentication-method: client_secret_post
          redirect-uri: http://localhost:8080/login/oauth2/code/kakao
          authorization-grant-type: authorization_code
          client-name: kakao
          scope:
            - profile_nickname
            - account_email
      provider:
        kakao:
          authorization-url: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id

python:
  connected:
    url: ${FLASK_SERVER_URL}

openai:
  model:
    id:
      a: ${OPENAI_MODEL_ID_A}
      b: ${OPENAI_MODEL_ID_B}
  api:
    key:
      b: ${OPENAI_API_KEY_B}